//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceStatus
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Text { get; set; }
        public string PlannedWorkHeadline { get; set; }
        public string Time { get; set; }
        public string Date { get; set; }
    }
}
