//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubwayLine
    {
        public SubwayLine()
        {
            this.SubwayLineWaits = new HashSet<SubwayLineWait>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double MeanWait { get; set; }
    
        public virtual ICollection<SubwayLineWait> SubwayLineWaits { get; set; }
    }
}
